### ISSUE TITLE
Conflicts with core s3Upload function

### ISSUE THREAD

**Issue by mojavelinux** [jenkinsci/pipeline-aws-plugin#123]
### Description

When this plugin is installed, it breaks all jobs that were already using the s3Upload pipeline function. The function in this plugin should be renamed so it doesn't cause a conflict.

### Steps to Reproduce

1. Install *Pipeline:  AWS Steps* plugin
2. Run a job that already uses the s3Upload function
3. Observe that the job now fails

**Expected behavior:** It should be possible to use both the s3Upload from the core Jenkins pipeline steps (https://jenkins.io/doc/pipeline/steps/core/#s3upload-publish-artifacts-to-s3-bucket) and the one provided by this plugin.

### Environment

**Jenkins-Version:** 2.89.7.1

**Java-Version:** n/a

**Plugin-Version:** 1.18

**Master/Slave Setup:** CloudBees

**Comment by hoegertn** [comment]
s3Upload seems to be part of https://github.com/jenkinsci/s3-plugin and not the core plugin. So I think you should decide which plugin you want to use for handling S3. Renaming this step would break the plugin for all users.

**Comment by mojavelinux** [comment]
While the S3 plugin may be packaged separately, it's core enough to be listed as a core step on the Jenkins website. It's also installed by default on CloudBees. The fact that you aren't even willing to discuss this request before closing it shows a disregard for compatibility with the ecosystem. As a result, I won't be using this plugin and I will recommend for my clients to avoid it.

**Comment by dragonfly-net** [comment]
Please, make alias for s3upload, like s3UploadAws. From s3-plugin - awful, i can't even set acl:publicRead with it! Only with lambda. No, IAM not working for us, we need make only some files worldread, not all.

**Comment by jonathannaguin** [comment]
Can this be re-open please?
