### ISSUE TITLE
Dynamic file paths for S3Upload

### ISSUE THREAD

**Issue by noviceamateur** [jenkinsci/pipeline-aws-plugin#130]
### Description

[Description of the bug or feature]

How to use environment variables in file path for s3Upload?

I want do something like this -
    s3Upload(file: '$JENKINS_HOME/jobs/xyzabc/branches/jenkins-test/builds/$BUILD_NUMBER/log',
                bucket: 'ess-jenkins-build-logs', path: '$BUILD_TAG')

But I dont think that the environment variables are being expanded in the file path parameter.
Using the latest plugin and jenkins version.

**Comment by hoegertn** [comment]
1) you have to use double quotes when doing expansion
2) you should use env.xx to access variables

```
s3Upload(file: "${$env.JENKINS_HOME}/jobs/xyzabc/branches/jenkins-test/builds/${env.BUILD_NUMBER}/log",
bucket: 'ess-jenkins-build-logs', path: "${env.BUILD_TAG}")
```

Can you try if this works?

**Comment by noviceamateur** [comment]
It worked. Thanks.
I should have searched. There was a similar ticket .
