### ISSUE TITLE
Make asumeRole using SAML assertion

### ISSUE THREAD

**Issue by benjaminrene** [jenkinsci/pipeline-aws-plugin#140]
### Description

When using withAWS(), there is no way to connect to AWS (creating a session token) with a SAML assertion and asume a role. We'd like to add a pram to withAWS step to be able to pass a SAML assertion and assume a role.
(https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/securitytoken/AbstractAWSSecurityTokenService.html#assumeRoleWithSAML-com.amazonaws.services.securitytoken.model.AssumeRoleWithSAMLRequest-)

### Steps to Reproduce

1. withAWS(role:'admin', roleAccount:'123456789012', region: ''eu-west-1', samlAssertion: '<assertionBase64>', principalArn: '') {...}
2. Session token created with success

**Expected behavior:** Assume a role with a SAML assertion

**Comment by hoegertn** [comment]
Can you elaborate on your use case? Where does the assertion come from?

Would you be able to implement this?

**Comment by benjaminrene** [comment]
This is for the company I work for, we pass through an Identification Portal that give us a SAML assertion to be authenticated on AWS. I cannot use the couple access_key_id + sercret_access_key because the session token can be provided once with this couple, and the only way to get one is to make a assumeRoleWithSAML with the assertion given by the IdP.
Am I clear ?

I have an other way to achieve the auth, by making myself the assumeRoleWithSAML and put the tuple access_key_id + sercret_access_key + aws_session_token in env vars that the plugin will read, I tried and it worked but it's messy and unsafe.

Yes I think i would be able to implement this use case, but i need to know how fast do you make a release when the feature will be ready ?

**Comment by hoegertn** [comment]
So and how does the Jenkins server get the SAML assertion?

When the code is there and working I can cut a release within one or two days.

**Comment by benjaminrene** [comment]
It will be in charge of the pipeline maintainer. In my case I have to make a HTTP request over the IdP with a LDAP user to get the SAML assertion in an HTML page (parse the web page returned).
I don't know if there is any standard to retrieve an assertion, but for sure in my case it's not...
Ok that's fine for me for the release process.

**Comment by benjaminrene** [comment]
Hi @hoegertn, are you OK to introduce this new feature in the plugin ? If you are, I can start my implementation right now.
Are you OK with the signature of `withAWS` in my first post too ?

Thanks for your answer.
