### ISSUE TITLE
s3Upload step doesn't allow to set object metadata with values containing colon character

### ISSUE THREAD

**Issue by bigunyak** [jenkinsci/pipeline-aws-plugin#141]
### Description

s3Upload step doesn't allow to set object metadata with values containing colon character.

### Steps to Reproduce

1. Try executing this.
```
s3Upload(bucket:"my-bucket", path:'path/to/targetFolder/', includePathPattern:'**/*.svg', workingDir:'dist', metadatas:['key:value1:value2'])
```

**Expected behavior:**
Object metadata should have `x-amz-meta-key` key with `value1:value2` value.

**Actual behavior:**
The metadata is missing with no errors.

### Environment

**Jenkins-Version:**
Jenkins ver. 2.121.3

**Java-Version:**

**Plugin-Version:**
1.29

**Master/Slave Setup:**
Slave

**Comment by hoegertn** [comment]
released with 1.35
