### ISSUE TITLE
withAWS() assumerole calls fail starting with v1.34 update

### ISSUE THREAD

**Issue by robzr** [jenkinsci/pipeline-aws-plugin#143]
### Description

withAWS() assumerole calls fail starting with v1.34 update

### Steps to Reproduce

1. Upgrade to v1.34
2. Try a withAWS(role: ...) without the region: argument

**Expected behavior:** [What you expected to happen]

Role will be changed

**Actual behavior:** [What actually happened]

Jenkins error with no output to the build log

### Environment

**Jenkins-Version:** [put your Jenkins version here]

2.138.1-alpine

**Java-Version:** [put your Java version here]

**Plugin-Version:** [put your plugin version here]

v1.34

**Master/Slave Setup:** [Do you run in a master/slave setup?]

No

**Comment by robzr** [comment]
It looks like this was broken in https://github.com/jenkinsci/pipeline-aws-plugin/issues/140 - just wanted to make sure you guys were aware of the extent of this and people coming to the issues page saw a report of it.

**Comment by hoegertn** [comment]
Thanks for the info. It is already fixed in 1.35. Sorry for the issue caused by this.

**Comment by robzr** [comment]
Thanks for the fast turnaround - and for your work on this!
