### ISSUE TITLE
Capabilities CAPABILITY_AUTO_EXPAND not implemented?

### ISSUE THREAD

**Issue by sufzoli** [jenkinsci/pipeline-aws-plugin#145]
This is just my gut feeling. I'm trying to use CAPABILITY_AUTO_EXPAND in cfnUpdate, but didn't find the way for it. Looked into the code and it looks like CAPABILITY_NAMED_IAM and CAPABILITY_IAM can be used but the autoexpand not.

**Comment by hoegertn** [comment]
I wanted to include this in the latest release but the underlying AWS-SDK plugin does not yet support this.
