### ISSUE TITLE
Get cfnUpdate status

### ISSUE THREAD

**Issue by chizou** [jenkinsci/pipeline-aws-plugin#146]
After executing cfnUpdate, I'd like to be able to perform actions based on the result of the update. The issue I'm dealing with is that if a job builds but no update occurs, then that's considered a success. This is fine, except I don't want to perform the same post action as I would if an update did occur. Can a way to query the status be returned to the pipeline?

**Comment by hoegertn** [comment]
The idea sounds cool. I will check if this is possible.

**Comment by hoegertn** [comment]
released with 1.36
