### ISSUE TITLE
Setting duration of withAWS() longer than 3600 seconds results in error.

### ISSUE THREAD

**Issue by mattemoore** [jenkinsci/pipeline-aws-plugin#150]
### Description

Setting duration property of withAWS() to a value longer than one hour in seconds causes pipeline to fail.

### Steps to Reproduce

withAWS in options block of declarative pipeline script:

1. withAWS(duration: 3599, region: AWS_REGION, role: AWS_ROLE, credentials: AWS_ID) - fine
     
2. withAWS(duration: 3600, region: AWS_REGION, role: AWS_ROLE, credentials: AWS_ID) - fine
     
3. withAWS(duration: 3601, region: AWS_REGION, role: AWS_ROLE, credentials: AWS_ID) - pipeline execution fails w/ 

> Required context class hudson.FilePath is missing
Perhaps you forgot to surround the code with a step that provides this, such as: node,dockerNode

**Expected behavior:** Proper error message or set to max AWS session of 3600

**Actual behavior:** Blows up pipeline with very unspecific error message.

**Comment by hoegertn** [comment]
I cannot reproduce this on my setup. Can you please post the pipeline code?

**Comment by mattemoore** [comment]
It would look like this:
```
pipeline {
    options {
        withAWS(duration: 3601, region: AWS_REGION, role: AWS_ROLE, credentials: AWS_ID) 
    }
}
```

**Comment by hoegertn** [comment]
This works in my test setup. Are durations longer than one hour allowed on your target role?
