### ISSUE TITLE
awaitDeploymentCompletion should end if deployment is stopped

### ISSUE THREAD

**Issue by KaelenProctor** [jenkinsci/pipeline-aws-plugin#163]
### Description

When a deployment is kicked off and then manually stopped before it ends, awaitDeploymentCompletion continues forever. 

### Steps to Reproduce

1. Trigger codedeploy (via AWS cli in our case)
2. Extract deployment ID from response
3. Use awaitDeploymentCompletion with the deployment ID
4. Using AWS console or CLI, stop the deployment using the deployment ID

**Expected behavior:** Since a stopped deployment cannot be restarted and nothing else is processing, the polling should end and an error triggered (same as if the deployment failed)

**Actual behavior:** Polling continues forever unless wrapped in a timeout block

### Environment

**Jenkins-Version:** 2.150.3

**Java-Version:** 	1.8.0_191

**Plugin-Version:** 1.3.6

**Master/Slave Setup:** No

**Comment by hoegertn** [comment]
I will try to look into it, but why would you want to trigger and abort deployments manually when using a CI/CD system?

**Comment by KaelenProctor** [comment]
At this time our CI/CD pipeline is not 100% automated and a human must choose the artifact to deploy, so error is possible. We happened to encounter this once when testing our pipeline for a new service, but not since we ironed out any issues with the pipeline and infrastructure.

**Comment by bbarhight** [comment]
It looks like this got addressed in this [commit](https://github.com/jenkinsci/pipeline-aws-plugin/commit/d88feb174215fc3b2cdba18afbd64f8e18037e0c) which was released in 1.3.9. Is this issue still relevant?

**Comment by KaelenProctor** [comment]
I just tested the scenario again in our setup with the plugin above version 1.3.9 and the await successfully stopped when the deploy was stopped manually. Thanks for resolving it!
