### ISSUE TITLE
s3Sync command unavailable? 

### ISSUE THREAD

**Issue by include** [jenkinsci/pipeline-aws-plugin#182]
### Description

As we have the `aws s3 sync` command; is there a simple way to mimic this behaviour with this pipeline-aws-plugin?

The Idea is to sync some directory like `build/*` from workspace to some S3 Bucket as we do with s3Upload.

In fact I want to clean my old files from S3; without wiping out all files with s3Delete... that's why the sync make sense for me; but let me know what you think and whats your solution to this.

Thanks,
F

**Comment by include** [comment]
used another (not so good approach) deleting first and then copying them again.

**Comment by captrespect** [comment]
It doesn't look like the java-aws sdk supports this with a simple command.  You'd probably have to do the diff yourself and then do all the uploads/downloads.

**Comment by ludrao** [comment]
I have the same issue, would not make it sense to provide an s3Sync step as part of this plugin ?

**Comment by ludrao** [comment]
For reference this is was the aws cli tool provides: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3/sync.html
