### ISSUE TITLE
Not all tasks run on the node, some execute on master

### ISSUE THREAD

**Issue by citizenkahn** [jenkinsci/pipeline-aws-plugin#187]
### Description
While s3Upload seems to execute on a node, awsIdentity and s3DoesObjectExist seem to run on master.  Given, that we usually sometimes assign IAM roles to specific nodes, it would be great if all the tasks behaved in a similar fashion and executed on the node in question (or had an option for that)
### Steps to Reproduce

We run this simple script and expect reported role to be that of the node in question

```
node('node-with-aws-role') {
    def identity = awsIdentity()
    println "AWS ID ${identity}"
}
```

However, this results in - Current AWS identity: ... - ...:i-... - arn:aws:sts::...:assumed-role/**jenkins-master-role**/i-... 

**Expected behavior:** [What you expected to happen]
I'd like all the steps to run on the node when wrapped in a node clause

**Actual behavior:** [What actually happened]
Some steps run on master and others on the node.  Should the step require file access (upload or download) then it appears to use the node in question.  If not, then it seems to run on master.

### Environment

**Jenkins-Version:** 2.181

**Java-Version:** 1.8.0_144-b01

**Plugin-Version:** 1.38

**Master/Slave Setup:** yes - both ec2 and ecs containers for slaves

**Comment by citizenkahn** [comment]
It seems that callable was only used for upload/download steps (which makes sense as it is really needed in that case).

**Comment by jgrammen-agilitypr** [comment]
This issue is also a problem for us. The authentication was granted to a jenkins agent node, but the plugin is looking for authentication on the master node.

**Comment by matandomuertos** [comment]
The same happens with cfnValidate, is running in master not in the agent node.

**Comment by djk** [comment]
Same issue here, renders plugin useless.

**Comment by hoegertn** [comment]
As discussed in several other issues, this is the intended behavior. Only file-specific steps are executed on the agent, everything else is executed on the main node, which is the expected behavior according to Jenkins.

**Comment by jgrammen-agilitypr** [comment]
could you please provide a reference to the Jenkins documentation stating that this is the expected behaviour? This would defeat the point of having many separate agent nodes and they will all be bottled necked by the executors on master. That seems very counter intuitive, if it is the intended behaviour

Thank you
Jason

**Comment by citizenkahn** [comment]
@hoegertn So, then using a policy and linking it a node via ecs node plugin or an ec2 ceases to be of use if there's no means of executing this code on a specific node.  Sure, I can get around the problem using shell or perhaps writing my own plugin.  Providing a hook to control the context would be very useful.  I get it, if it's not a priority.
