### ISSUE TITLE
withAWS step credentials expire and don't auto renew

### ISSUE THREAD

**Issue by shadycuz** [jenkinsci/pipeline-aws-plugin#189]
### Description

When doing role chaining you are limited to an hour of duration. https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use.html

> ¹ Using the credentials for one role to assume a different role is called role chaining. When you use role chaining, your new credentials are limited to a maximum duration of one hour.

When using AWS orgs we assume a role into the master account, find the information for the child account and then assume a role into that account. For certain long-running deployments like deploying stack sets to many accounts and regions, we need more than an hour. 

What we have found is that for our exiting python scripts you can actually create refreshing AWS credentials that refresh in the background for you. We followed this guide https://dev.to/li_chastina/auto-refresh-aws-tokens-using-iam-role-and-boto3-2cjf and it works great.

I tried to implement this with the aws java SDK... first using 1.11 and then v2. I failed both times. You can see me reaching out for help https://gitter.im/aws/aws-sdk-java-v2 with no luck. Not really a java guy. I'm not even sure you can implement this with the AWS SDK. It does have some classes that auto-refresh that I'm having issues getting it to work correctly. I think between looking at your code and the aws example I might be able to get it work.

### Steps to Reproduce
```Groovy
withAWS(role: ${masterRoleName}, roleAccount: ${masterAccountID}, duration: '900', roleSessionName:  ${env.JOB_NAME}) {
    withAWS(role: ${childRoleName}, duration: '900', roleSessionName:  ${env.JOB_NAME}) {
        sh('sleep 18m')
        sh('aws s3 ls')
    }
}
```
**Expected behavior:** [What you expected to happen]
I expected to see a list of buckets
**Actual behavior:** [What actually happened]
I get an error that my creds have expired

### Environment

**Jenkins-Version:** [put your Jenkins version here]
Docker LTS
**Java-Version:** [put your Java version here]
Idk
**Plugin-Version:** [put your plugin version here]
latest?
**Master/Slave Setup:** [Do you run in a master/slave setup?]
yes but not when developing locally (docker)

**Comment by shadycuz** [comment]
okay, so for `withAWS` this doesn't make any sense. Unless you can somehow in a background thread, refresh the environments credentials you are exporting. 

It still might help though on some of your other steps that might be long-running. I eventually got it to work with `STSAssumeRoleSessionCredentialsProvider` but I'm currently testing right now if it actually refreshes credentials. 

Will leave this up for now. Feel free to close.

**Comment by IuryAlves** [comment]
I am also  interested in this. It would be nice if `withAWS` could auto renew the session.

**Comment by hoegertn** [comment]
I don't think this is possible as the withAWS step is called once and sets temporary credentials. I have no idea how I should refresh them when they expire.
