### ISSUE TITLE
Getting JAVA exception when setting region parameter in withAWS()

### ISSUE THREAD

**Issue by ZillaG** [jenkinsci/pipeline-aws-plugin#194]
### Description
I set the following parameters in withAWS() call
`withAWS(region:'us-east-1',credentials: 'AWS Jenkins') { // do something}`
and get
`java.lang.IllegalArgumentException: Cannot create enum from 'us-east-1 value! `

[Description of the bug or feature]
I set the following parameters in withAWS() call
`withAWS(region:'us-east-1',credentials: 'AWS Jenkins') { // do something}`
and get
`java.lang.IllegalArgumentException: Cannot create enum from 'us-east-1 value! `

### Steps to Reproduce

1. [First Step]
Setup a pipeline with a withAWS() call with above parameters
2. [Second Step]
Run the pipeline
3. [and so on...]

**Expected behavior:** [What you expected to happen]
I should NOT get an exception

**Actual behavior:** [What actually happened]
I get above exception
### Environment

**Jenkins-Version:** [put your Jenkins version here]
2.164.3

**Java-Version:** [put your Java version here]
openjdk version "1.8.0_222" on Ubuntu box

**Plugin-Version:** [put your plugin version here]
1.38

**Master/Slave Setup:** [Do you run in a master/slave setup?]
I have a separate master and slaves.

**Comment by hoegertn** [comment]
Can you make sure, that both `'` around the region are normal ticks? It might be a parsing error.

**Comment by ZillaG** [comment]
This was user error so I'm closing it. I wasn't wrapping one of my cfnUpdate() calls with withAWS()
