### ISSUE TITLE
S3 Exclude multiple files

### ISSUE THREAD

**Issue by nugaon** [jenkinsci/pipeline-aws-plugin#199]
### Description

With the AWS CLI it is possible to pass multiple --exclude parameter, thereby multiple files can be omitted from the upload list separately like *.jpg, .*png, bundle.js, etc.
I didn't find any examples for pass multiple patterns for the `excludePathPattern` parameter, like `excludePathPattern: 'index.html;bundle.js;assets/logo.png` or similar like this. 
There is any possibility to set mutiple files/folders for the exclude parameter?

### Environment

**Jenkins-Version:** 2.176.3

**Java-Version:** 1.8

**Plugin-Version:** 1.38

**Comment by ksmith97** [comment]
I had this same question, so I traced through the code and found that it delegates to hudson.Util#createFileSet which allows for multiple glob patterns separated by a ",". I verified this worked on my local project.
