### ISSUE TITLE
excludePathPattern not applied

### ISSUE THREAD

**Issue by lobeck** [jenkinsci/pipeline-aws-plugin#200]
### Description

I'm trying to upload everything from a directory:

    s3Upload(pathStyleAccessEnabled: true, payloadSigningEnabled: true, file: '.', bucket: params.BUCKET, path: '', excludePathPattern: '**/.git/**')

I tried various versions of `excludePathPattern`, but the files always get uploaded.

### Steps to Reproduce

Tried the following values already. None of them seem to have been applied. I've also noticed, that `defaultExcludes` is passed as `true`, which should exclude .git by default, but it doesn't.

    **/.git/**
    Jenkinsfile
    **/.git/*,**/Jenkinsfile
    **/.git/*,/Jenkinsfile
    .git/*,/Jenkinsfile
    .git/*
    .git/*,Jenkinsfile

**Expected behavior:** 

The files get skipped

**Actual behavior:** 

The files are uploaded

### Environment

**Jenkins-Version:** 2.194

**Java-Version:** OpenJDK 1.8.0_222

**Plugin-Version:** 1.38

**Master/Slave Setup:** yes

**Comment by sandeep-qantas** [comment]
I faced the same issue today, and got it resolved with below fix,

`excludePathPattern` is not applied by the s3upload api when `file` attribute is used, to get this applied, we have to use `workingDir`

below code can't work:
`s3Upload(file: "./tmp/", bucket: "bucket-name", path: "bucket-path",  excludePathPattern:"*.txt")`

below code will work:
`s3Upload(workingDir: "./tmp/", bucket: "bucket-name", path: "bucket-path", excludePathPattern:"*.txt")`
