### ISSUE TITLE
s3Delete don't work with IAM EC2 Role

### ISSUE THREAD

**Issue by muanGC** [jenkinsci/pipeline-aws-plugin#209]
### Description

Hi! We use IAM Role EC2 in a Jenkins Agent machine to upload things to S3, we use the S3Upload and it works as expected, but when we use S3Delete it fails.

If I use withAWS credentials (iam user credentials) s3Delete Works.

### Steps to Reproduce

Create a Jenkinsfile with pipeline syntax like:
```
  withAWS(region: 'us-east-1') {
    s3Delete(bucket: "bucket-name", path: '/')
    s3Upload(file: 'folder', bucket: "bucket-name", path: '/', acl: 'PublicRead')
  }
```

If I remove s3Delete line, the s3Upload works as expected (using iam ec2 role), but s3Delete without credentials (using iam ec2 role) don't work.

ps. The IAM Role has the right permissions.

**Expected behavior:** The bucket be cleared
**Actual behavior:** 
```
com.amazonaws.SdkClientException: Unable to load AWS credentials from any provider in the chain: [EnvironmentVariableCredentialsProvider: Unable to load AWS credentials from environment variables (AWS_ACCESS_KEY_ID (or AWS_ACCESS_KEY) and AWS_SECRET_KEY (or AWS_SECRET_ACCESS_KEY)), 
SystemPropertiesCredentialsProvider: Unable to load AWS credentials from Java system properties (aws.accessKeyId and aws.secretKey), 
com.amazonaws.auth.profile.ProfileCredentialsProvider@2300a6df: profile file cannot be null, 
WebIdentityTokenCredentialsProvider: You must specify a value for roleArn and roleSessionName, 
com.amazonaws.auth.EC2ContainerCredentialsProviderWrapper@c5ff958: The requested metadata is not found at http://169.254.169.254/latest/meta-data/iam/security-credentials/]
```

### Environment

**Jenkins-Version:** 2.190.2

**Java-Version:** 1.8.0_232

**Plugin-Version:** 1.39

**Master/Slave Setup:** no

**Comment by hoegertn** [comment]
s3Delete is executed on the master as it does not touch the workspace. I am open for PRs for full agent support.

**Comment by muanGC** [comment]
Oh! thanks for the information, I will study if I can do this change and do the PR, thanks!
