### ISSUE TITLE
withAWS credentials + account

### ISSUE THREAD

**Issue by alexey-pelykh** [jenkinsci/pipeline-aws-plugin#216]
### Description

Right now there's no way to specify account that we want to use for withAWS

### Steps to Reproduce

```
// TODO: withAWS can not set account ID
sh "\$(aws --region $env.AWS_REGION ecr get-login --registry-ids $env.AWS_ACCOUNT --no-include-email)"
//withAWS(roleAccount: "${env.AWS_ACCOUNT}", region:"${env.AWS_REGION}", credentials:'infr-ecr-publisher') {
// sh "${ecrLogin()}"
//}
```

**Comment by hoegertn** [comment]
I am not sure I understand what you mean. ecrLogin uses the current account. Using `withAWS` you can assume roles in another account and then use `ecrLogin` there. It is not meant to create an env variable `AWS_ACCOUNT` for later use.

**Comment by alexey-pelykh** [comment]
@hoegertn sorry for confusion, let me re-express what I mean:
We have an AWS organization where are two accounts, A and B. User is created in account B, and ECR is in account B, but default accounts is A. If I use `withAWS` and supply that user credentials and proper AWS region, `ecrLogin` still tries to get login for account A, that results in an issue. So I need to somehow explicitly set AWS account for this.

**Comment by alexey-pelykh** [comment]
Hm, maybe it's related to this line https://github.com/jenkinsci/pipeline-aws-plugin/blob/4c92a56074c4227428ab43e1b2d34f72165f9298/src/main/java/de/taimos/pipeline/aws/ECRLoginStep.java#L99 where it should be possible to pass an account

**Comment by alexey-pelykh** [comment]
https://github.com/jenkinsci/pipeline-aws-plugin/pull/217 this is what I mean

**Comment by AndrGrig** [comment]
Hi, 
After this conversation, I have the following question.
After I logged in and received a token, how can I push the docker image to the repository?

For example:
def login = ecrLogin(registryIds: [account_id])
println "Get token: "+login
sh(login) <----- Here I logged in to the ECR and get the message: "Login Succeeded"

What is the next step?

Thanks in advance.

**Comment by cullenp** [comment]
Hi AndrGrig,

You can follow your ecrlogin step with a docker push step the token should remain valid and stored by the environment while your pipeline runs.

`        stage("ECR Login") {
            steps {
                withAWS(credentials:'your-jenkins-credentials-id') {
                    script {
                        def login = ecrLogin()
                        sh "${login}"
                    }
                }
            }
        }
        stage("Docker push to AWS ECR for develop branch") {
            when {
                branch 'develop'
            }
            environment {
                gcs = "${sh(script:'echo -n ${GIT_BRANCH_NAME,,}-${GIT_COMMIT:0:8}', returnStdout: true).trim()}"
            }
            steps {
                sh "docker tag ${ecr_repo}:latest ${registry}/${ecr_repo}:$gcs"
                sh "docker push ${registry}/${ecr_repo}:$gcs"
                sh "docker tag ${ecr_repo}:latest ${registry}/${ecr_repo}:latest"
                sh "docker push ${registry}/${ecr_repo}:latest"
            }
        }`
