### ISSUE TITLE
metadata content-disposition support

### ISSUE THREAD

**Issue by nehagupta29** [jenkinsci/pipeline-aws-plugin#239]
### Description

I am unable to set content-disposition metadata using aws pipeline. I can submit the change request but unable to push my changes to this repo. Can someone please add this support or give me necessary permissions to create a pull request?
github account: NEHAGUPTA2988@GMAIL.COM

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Environment

**Jenkins-Version:** [put your Jenkins version here]

**Java-Version:** [put your Java version here]

**Plugin-Version:** [put your plugin version here]

**Master/Slave Setup:** [Do you run in a master/slave setup?]

**Comment by hoegertn** [comment]
https://github.com/jenkinsci/pipeline-aws-plugin/issues/166#issuecomment-664981158
