### ISSUE TITLE
Passing ACCESS_KEY and SECRET_KEY withAWS

### ISSUE THREAD

**Issue by hirenoble** [jenkinsci/pipeline-aws-plugin#246]
[X] 🐞 Bug
[ ] 🚀 Feature
[ ] 🛠 Task
[ ] 📄 Documentation

### Description
Currently, withAWS only works with stored credentials and required a credentialsId, since I'm retrieving AWS ACCESS_KEY and SECRET_KEY using hashicorp vault in pipeline, there is no way to pass ACCESS_KEY and SECRET_KEY withAWS step.

[Description of the bug or feature]
It would be great if withAWS supports passing inline ACCESS_KEY and SECRET_KEY instead of credentialsId.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Environment

**Jenkins-Version:** [put your Jenkins version here]

**Java-Version:** [put your Java version here]

**Plugin-Version:** [put your plugin version here]

**Master/Slave Setup:** [Do you run in a master/slave setup?]

**Comment by hoegertn** [comment]
You should be able to skip the whole withAWS and just set the two values as environment variables using `export`
