### ISSUE TITLE
Release new Version with elastic beanstalk support

### ISSUE THREAD

**Issue by maxlmo** [jenkinsci/pipeline-aws-plugin#259]
[x] 🛠 Task

#### Release new Version with elastic beanstalk support

I'am using your plugin right now for a upload to S3 and would love to create the deployment within elastic beanstalk aswell.
Do you already know, when you are going to release this feature set?

FYI: It seems to me https://plugins.jenkins.io/pipeline-aws is pointing to your master, because it already displays the new feature set :)

**Comment by hoegertn** [comment]
This was released with 1.43
