### ISSUE TITLE
Need a JAR file for this plugin

### ISSUE THREAD

**Issue by ShreyasSubhedar** [jenkinsci/pipeline-aws-plugin#269]
- [ ] 🐞 Bug
- [x]  🚀 Feature
- [ ] 🛠 Task
- [ ] 📄 Documentation

### Description

I want the JAR file for this plugin so that I can mock the behaviour using homeway Jenkins SPOCK testing framework

**Comment by hoegertn** [comment]
You should be able to download it from the build server by clicking on the build badge on the start page o this repo

**Comment by ShreyasSubhedar** [comment]
@hoegertn  thanks for the direction , later I checked the `pom.xml` & got the groupId as well -> `de.taimos`
