### ISSUE TITLE
s3Delete fails with "403 Forbidden" when target is a folder

### ISSUE THREAD

**Issue by sdanieru** [jenkinsci/pipeline-aws-plugin#270]
[X] 🐞 Bug

### Description

`s3Delete()` successfully deletes target specified in the file format (.e.g. `path/to/source/file.txt'`) but always fails with `Error Code: 403 Forbidden` whenever target is specified in folder format (e.g. `path/to/sourceFolder/`)

### Steps to Reproduce

1. Setup a bucket with various files; some of those  files in 'folders'
2. Setup an appropriate policy that allows the `deleteObject` action
3. use `s3Delete()` on a single file to verify you have proper permissions
4. Attempt to use `s3Delete()` on a folder (e.g. `path/to/sourceFolder/`) to delete all contents of the folder

**Expected behavior:** `s3Delete()` successfully deletes all files in folder when specified in folder format, i.e. ending in a '/'. 

**Actual behavior:** specifying a delete in a folder format fails with `Error Code: 403 Forbidden`. I'm seeing consistent failure both when specifying sub-directories (e.g. `myFolder/` as well as the root of the bucket `/`)
### Environment

**Jenkins-Version:** 2.235.5

**Java-Version:** openjdk version "1.8.0_201"

**Plugin-Version:** 1.43

**Master/Slave Setup:** `ec2-fleet-plugin` launches on demand workers

**Comment by hoegertn** [comment]
Did you try the proposed solution in #63 ?

**Comment by sdanieru** [comment]
yes, that did the trick, much thanks!
