### ISSUE TITLE
New tag for master changes? Need bug fix for #264

### ISSUE THREAD

**Issue by sr75** [jenkinsci/pipeline-aws-plugin#288]
There's several changes in master, but we don't pull from master.

The bug fix we need is https://github.com/jenkinsci/pipeline-aws-plugin/issues/264 and there's others.

Can we get a new tag created that includes all the changes in master?

**Comment by chickenland** [comment]
Hey @sr75 did you resolve this?  Unsure how to get the latest so I can pull in this fix also.

**Comment by floriankick** [comment]
Could you please release a new Version to the Jenkins Plugins Index.
I still have the problem from https://github.com/jenkinsci/pipeline-aws-plugin/issues/264. It was fixed more than 2 years ago, but the current version still doesn't contain the fix.
