### ISSUE TITLE
s3Upload fails to upload file to the s3 bucket with Content-MD5 metadata

### ISSUE THREAD

**Issue by ADobrodey** [jenkinsci/pipeline-aws-plugin#40]
**What is the expected result?**
```
String md5Base64 = sh(
      returnStdout: true,
      script: 'openssl md5 -binary ./foo.zip | base64'
).trim()

s3Upload(
    file: './foo.zip',
    bucket: 'bar',
    path: 'foo/bar/foo.zip',
    metadatas: [
       "Content-MD5:${md5Base64}"
    ]                
)
```
s3Upload fuction uploads file to the s3 bucket

**What happens instead?**
Getting:

> java.io.IOException: Bad file descriptor
> 	at sun.nio.ch.FileChannelImpl.position0(Native Method)
> 	at sun.nio.ch.FileChannelImpl.position(FileChannelImpl.java:264)
> 	at com.amazonaws.internal.ResettableInputStream.<init>(ResettableInputStream.java:113)
> 	at com.amazonaws.internal.ResettableInputStream.<init>(ResettableInputStream.java:101)
> 	at com.amazonaws.internal.ResettableInputStream.newResettableInputStream(ResettableInputStream.java:300)
> Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from ip-10-114-129-97.ec2.internal/10.114.129.97:41483
> 		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1693)
> 		at hudson.remoting.UserResponse.retrieve(UserRequest.java:310)
> 		at hudson.remoting.Channel.call(Channel.java:908)
> 		at hudson.FilePath.act(FilePath.java:986)
> 		at hudson.FilePath.act(FilePath.java:975)
> 		at de.taimos.pipeline.aws.S3UploadStep$Execution$1.run(S3UploadStep.java:250)
> Caused: com.amazonaws.SdkClientException
> 	at com.amazonaws.internal.ResettableInputStream.newResettableInputStream(ResettableInputStream.java:302)
> 	at com.amazonaws.internal.ResettableInputStream.newResettableInputStream(ResettableInputStream.java:277)
> 	at com.amazonaws.internal.ReleasableInputStream.wrap(ReleasableInputStream.java:129)
> 	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1606)
> 	at com.amazonaws.services.s3.transfer.internal.UploadCallable.uploadInOneChunk(UploadCallable.java:133)
> 	at com.amazonaws.services.s3.transfer.internal.UploadCallable.call(UploadCallable.java:125)
> 	at com.amazonaws.services.s3.transfer.internal.UploadMonitor.call(UploadMonitor.java:143)
> 	at com.amazonaws.services.s3.transfer.internal.UploadMonitor.call(UploadMonitor.java:48)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)

Thank you in advance.

**Comment by hoegertn** [comment]
setting the ContentMD5 using the metadatas parameter is not supported, as it only sets user metadata. But I could add a new parameter if this is needed. What is your use case of not letting S3 determine the md5 hash?
