### ISSUE TITLE
ExecuteChangeSet logic fails when stack is created instead of updated

### ISSUE THREAD

**Issue by cast** [jenkinsci/pipeline-aws-plugin#43]
The logic at the line below fails when the stack is created instead of updated:

https://github.com/jenkinsci/pipeline-aws-plugin/blob/a9c9fdc7756f2f6528e8c47497d2441d8ca0c132/src/main/java/de/taimos/pipeline/aws/cloudformation/CloudFormationStack.java#L205

There should be an additional branch when the stack does not exist. Currently the jenkins job keeps waiting and can't continue when a new stack is created instead of being updated.

**Comment by hoegertn** [comment]
released with 1.22
