### ISSUE TITLE
s3Upload cannot set content type

### ISSUE THREAD

**Issue by adibendahan** [jenkinsci/pipeline-aws-plugin#44]
Hi, 
I am attempting to upload a JSON file and set the content type to "application/json" but using the following syntax uploads the file with the default content type "application/octet-stream":

`s3Upload(file:"$file_name", bucket:'bucketname', path:"$file_name", acl:'PublicRead', contentType:'application/json')`

I also attempted to do it with the following syntax but I got an exception "java.io.IOException: Bad file descriptor":
`s3Upload(file:"$file_name", bucket:'bucketname', path:"$file_name", acl:'PublicRead', metadatas:['Content-Type:application/json'])`
`s3Upload(file:"$file_name", bucket:'bucketname', path:"$file_name", acl:'PublicRead', metadatas:['ContentType:application/json'])`

Am I doing something wrong?
Thanks for the help!

**Comment by adibendahan** [comment]
Looks like if I replace the order of the parameters it works:
`s3Upload(file:"$file_name", bucket:'bucketname', path:"$file_name", contentType:'application/json', acl:'PublicRead')`

**Comment by hoegertn** [comment]
are you sure the first did not work? The order of the parameters should not matter.

**Comment by adibendahan** [comment]
Double checked it now, does not work for me when the contentType parameters is last (like on my first post).

**Comment by adibendahan** [comment]
wait, now it doesn't work again.

No idea why sometimes it works and sometimes it doesn't...

**Comment by hoegertn** [comment]
does this happen with the latest plugin version too? (1.22)

**Comment by adibendahan** [comment]
I am using 1.18, updating now and will let you know how it goes...

**Comment by adibendahan** [comment]
@hoegertn updating to 1.22 resolved the issue, thank you for the help!
