### ISSUE TITLE
Jenkins Pipeline S3 Upload: missing file

### ISSUE THREAD

**Issue by gvasquez-waypoint** [jenkinsci/pipeline-aws-plugin#53]
Please see full details at https://stackoverflow.com/questions/48771407/jenkins-pipeline-s3-upload-missing-file

**Comment by hoegertn** [comment]
Hi, great catch. There indeed is a corner case where this fails when the pattern matches exactly one file. I will add a fix a release it with the next version coming this weekend.

**Comment by gvasquez-waypoint** [comment]
Great @hoegertn such a quick response with an already covered issue...I'll be expecting the next release to add it to our Jenkins setup. Hope you can notify me when it's available.

**Comment by hoegertn** [comment]
Should be released

**Comment by gvasquez-waypoint** [comment]
It's released and fixed indeed! Thanks a lot for such a fast timing.
