### ISSUE TITLE
S3 upload fails to upload if only one file is matched by include.

### ISSUE THREAD

**Issue by zepag** [jenkinsci/pipeline-aws-plugin#55]
Easy to reproduce with a local Minio S3 server:
```
withAWS(endpointUrl:'http://127.0.0.1:9000',credentials:'s3-repo-credentials'){   
   s3Upload bucket:'mybucket', includePathPattern: '*', path: 'anyfolder/', workingDir: 'anyfolder/'
}
```
if `anyfolder/` does contain only one file, upload will **fail** saying there is a forbidden character.
Add any additional matching file in the folder, and the upload works fine.
There must be a difference between the single file and multiple files path somewhere down the line (haven't found it yet otherwise this would a PR and not an issue ;) ).

I'll attach more details as soon as I have some time to monitor the issue at the level of the Minio server (which incoming request gets there).

**Comment by hoegertn** [comment]
Hi, did you try the latest version released yesterday? I fixed some issue with exactly this use case

**Comment by zepag** [comment]
Not yet I must admit. I'd have to test it on a blank node though, as upgrading pipelines will likely break other stuff I use currently.

**Comment by zepag** [comment]
Tested, the issue as described here is solved :1st_place_medal:

**Comment by zepag** [comment]
Thanks :)
