### ISSUE TITLE
Hiding output of ecrLogin() when running sh

### ISSUE THREAD

**Issue by hibbert** [jenkinsci/pipeline-aws-plugin#58]
When doing the following

withAWS() {
   def login = ecrLogin()
   sh login
}

Is there a way of hiding the docker login string. I've tried the usual

def docker_login = sh(returnStdout: false, script: login)

But it still prints it in the console log

**Comment by thisismana** [comment]
`sh` is providing a `sh`/`bash` in debug mode. Its like doing a `set -x` in your script.

> -x Print a trace of simple commands, for commands, case commands, select commands, and arithmetic for commands and their arguments or associated word lists after they are expanded and before they are executed. The value of the PS4 variable is expanded and the resultant value is printed before the command and its expanded arguments.

If this is new to you, have a look at the man page: `man bash`.

What you could do is to manually insert a shebang to prevent the `sh` from starting in debug mode:

    sh """#!/usr/bin/env bash
      ${ecrLogin()}
    """

Or simply disable the verbos flag:

    sh "set +x; ${ecrLogin()}"

(but this still prints `set +x` to the console whereas the first variant (shebang) doesn't print anything except `Login Succeeded`)
