### ISSUE TITLE
lambda update-function-code support

### ISSUE THREAD

**Issue by harshana-rav** [jenkinsci/pipeline-aws-plugin#60]
I wonder if you have plans for support `lambda update-function-code` ? we do a lot of lambda development and it would be fantastic if the plugin supported `lambda update-function-code`. 

also wonder if you know a alternative to do `lambda update-function-code` from the pipeline

**Comment by hoegertn** [comment]
Currently, I do not plan this. I recommend deploying lambdas using CloudFormation (and SAM if possible).

**Comment by aantono** [comment]
Do you have an example of how that could be done using the cfn pipeline steps?

**Comment by hoegertn** [comment]
If you create CloudFormationtemplates to deploy your Lambda code, you can use the cfnCreateChangeset and cfnExecuteChangeSet steps to deploy these templates to AWS.
