### ISSUE TITLE
Allow to empty bucket

### ISSUE THREAD

**Issue by SamVerschueren** [jenkinsci/pipeline-aws-plugin#63]
I tried to use `s3Delete(bucket: 'my-bucket', path: '')` to empty a bucket and remove all the files. But then it throws an error 

> The bucket you tried to delete is not empty 

I don't want to delete the bucket, I want to delete the files in the bucket. I tried setting path to `.` but still the same thing. With `/` it didn't delete anything.

Any ideas?

**Comment by hoegertn** [comment]
Indeed the case of the "folder" being the bucket root is not implemented. I will try to have a look at it. As a workaround, you can use a combination of s3FindFiles and s3Delete.

**Comment by hoegertn** [comment]
Will be released with 1.25 and you have to use `s3Delete(bucket: 'my-bucket', path: '/')` to empty the bucket

**Comment by SamVerschueren** [comment]
Awesome! Thank you for the quick response :beers:!

**Comment by sdanieru** [comment]
@hoegertn are there any actions in addition to `s3:DeleteObject` that need to be allowed for `s3Delete(bucket: 'my-bucket', path: '/')` to empty the bucket? With `s3:DeleteObject`, I'm getting:

`com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden`

**Comment by hoegertn** [comment]
To find all the objects it also needs `s3:ListBucket` permission
