### ISSUE TITLE
Uploading 10 byte file took four minutes

### ISSUE THREAD

**Issue by nickgravelyn** [jenkinsci/pipeline-aws-plugin#66]
I'm getting started with this plugin and it seems like there's something odd happening with performance. Here's my entire test pipeline:

    pipeline {
        agent any

        options {
            timestamps()
            disableConcurrentBuilds()
            timeout(time: 1, unit: 'HOURS')
        }
        
        stages {
            stage('doit') {
                steps {
                    bat returnStatus: true, script: 'echo "Hello" > test.txt'
                    s3Upload acl: 'BucketOwnerFullControl', bucket: 'my-cool-bucket', file: 'test.txt', path: 'test.txt'
                }
            }
        }
    }

When I ran this it took nearly four minutes to upload the test file:

    [Pipeline] bat
    00:00:05.357 [UploadToS3Test] Running batch script
    00:00:09.359 
    00:00:09.359 c:\jenkins\workspace\UploadToS3Test>echo "Hello"  1>test.txt 
    [Pipeline] s3Upload
    00:00:12.101 Uploading file:/c:/jenkins/workspace/UploadToS3Test/test.txt to s3://my-cool-bucket/test.txt 
    00:04:06.186 Finished: Uploading to my-cool-bucket/test.txt
    00:04:07.845 Upload complete

Is that really expected? Is there something else that could be causing the job to be so slow? There's no other logging information during that nearly four minute gap so I don't know where to begin looking. I am using Jenkins 2.113 and Pipeline: AWS Steps plugin 1.24, which are the latest as of today.

**Comment by nickgravelyn** [comment]
Also for comparison I replaced the s3Upload call with a PowerShell script using the AWS plugin tools and it took it only a few seconds:

    pipeline {
        agent any

        options {
            timestamps()
            disableConcurrentBuilds()
            timeout(time: 1, unit: 'HOURS')
        }
        
        stages {
            stage('doit') {
                steps {
                    bat returnStatus: true, script: 'echo "Hello" > test.txt'
                    powershell 'Write-S3Object -BucketName my-cool-bucket -Key test.txt -File test.txt -Force'
                }
            }
        }
    }

    00:00:00.395 Timeout set to expire in 1 hr 0 min
    [Pipeline] {
    [Pipeline] stage
    [Pipeline] { (doit)
    [Pipeline] bat
    00:00:04.363 [UploadToS3Test] Running batch script
    00:00:08.371 
    00:00:08.371 c:\jenkins\workspace\UploadToS3Test>echo "Hello"  1>test.txt 
    [Pipeline] powershell
    00:00:16.374 [UploadToS3Test] Running PowerShell script

    [Pipeline] }
    [Pipeline] // stage
    [Pipeline] }
    [Pipeline] // timeout
    [Pipeline] }
    [Pipeline] // timestamps
    [Pipeline] }
    [Pipeline] // node
    [Pipeline] End of Pipeline
    Finished: SUCCESS

**Comment by hoegertn** [comment]
Are you using a master/agent setup?

What happens if you do another upload right after the first one? Is it faster?

What happens on subsequent runs of the job?

**Comment by nickgravelyn** [comment]
So I went back to try running two uploads as you suggested and it's now incredibly fast:

    00:00:04.136 [UploadToS3Test] Running batch script
    00:00:08.137 
    00:00:08.137 c:\jenkins\workspace\UploadToS3Test>echo "Hello"  1>test.txt 
    [Pipeline] s3Upload
    00:00:11.138 Uploading file:/c:/jenkins/workspace/UploadToS3Test/test.txt to s3://my-cool-bucket/test1.txt 
    00:00:13.139 Finished: Uploading to my-cool-bucket/test1.txtUpload complete
    00:00:13.140 
    [Pipeline] s3Upload
    00:00:14.139 Uploading file:/c:/jenkins/workspace/UploadToS3Test/test.txt to s3://my-cool-bucket/test2.txt 
    00:00:16.140 Finished: Uploading to my-cool-bucket/test2.txt
    00:00:16.140 Upload complete

I tried playing with the target path to see if having it with the same name as my file mattered, but it doesn't. Seems to be working fine now but that's really odd why repeated runs would change that much. I will come back if I have issues, but it seems to be resolved.

Sorry for the trouble!

**Comment by hoegertn** [comment]
Are you using a master/agent setup? Maybe the transfer of the plugin code to the agent takes some time if the connection from master to agent is slow.

**Comment by nickgravelyn** [comment]
It is a master/agent setup. Both VMs are running in the same region of AWS so I wouldn't expect it to be terribly slow unless there's a lot of code to move over in the first invocation.

**Comment by isuftin** [comment]
@hoegertn FYI I am seeing this issue as well and the file to upload exists on the slave. I'm not sure what I should be doing to get around this?

**Comment by VladimirIordanov** [comment]
I have the same issue. Most time s3Upload is very fast, but sometimes it is extremely slow. And this slowness can happen in random period of time. 
In my Jenkins job I use sequence of s3Download and s3Upload:
`
            for (file in files) {
                copyS3File(
                        file.name,
                        prodBucket,
                        stageBucket,
                        filesPath,
                        prodRole,
                        prodAccount,
                        stageRole,
                        stageAccount
                )
            }
`
Definition of copyS3File is:
`
def copyS3File(fileName, prodBucket, stageBucket, path, prodRole, prodAccount, stageRole, stageAccount)
{
    // Download data files
    withAWS(role: prodRole, roleAccount: prodAccount) {
        s3Download(file: fileName, bucket: prodBucket, path: "$path/$fileName", force: true)
    }
    // Upload data files
    withAWS(role: stageRole, roleAccount: stageAccount) {
        s3Upload(file: fileName, bucket: stageBucket, path: "$path/$fileName")
    }
    // Finally delete the file from workspace
    sh "rm -f $fileName"
}
`
Any suggestion how to fix this issue?

**Comment by chrisj-au** [comment]
Experiencing this also.  We're using on-demand agents (Windows) and it takes ~10 minutes to upload a very small file using s3upload(file: xxx) but only on the first file upload per agent.  So any subsequent calls to s3upload(file: xxx) is very fast., whether that's within the same pipeline, or subsequent pipeline runs (so the same line runs instantly a second time on the same agent).

Work around for small files is to use s3upload(text: xxx) instead, it never has the delay which would suggest it's not the plugin xfer to the agent?:
`
def fileContent = readFile(file: <file>)
s3upload(text: fileContent, ....)
`
