### ISSUE TITLE
cfnExecuteChangeSet timing out when creating a new stack, but stack creates successfully

### ISSUE THREAD

**Issue by KenHundley** [jenkinsci/pipeline-aws-plugin#67]
Hi, 
We are running into an issue when creating new CFN stacks using cfnCreateChangeSet and cfnExecuteChangeSet. The change set for the new stack is created without issue, but when we execute that changeset we run into problems, but only when the stack is new. The stack creates without issue in CFN, but the Jenkins plugin does not detect that the creation is complete and just hangs until it eventually times out with `com.amazonaws.waiters.WaiterTimedOutException: Reached maximum attempts without transitioning to the desired state`

Looking at the logs in Jenkins I see the CREATE_COMPLETE event for the stack, but that's the last log entry before the hang and eventual timeout. After the stack is created we can rerun the build and there are 0 issue while updating the existing stack. We have only seen this issue while creating brand new stacks. 

Unfortunately we can't use cfnUpdate to create the initial stack because we are using AWS::Serverless resources that require the use of change sets to deploy.

**Comment by KenHundley** [comment]
Also, I have verified that we are running the latest version of the plugin

**Comment by hoegertn** [comment]
Thanks for the catch. Fixed it.

**Comment by KenHundley** [comment]
Great @hoegertn, ty for fixing that. Any idea when this might be released?

**Comment by hoegertn** [comment]
Plugin is released as 1.25. Should be available within hours.

**Comment by starrett67** [comment]
@hoegertn I started getting this same error while running an invalidation. I noticed that the invalidations are taking a while.
