### ISSUE TITLE
SQS Publish Support

### ISSUE THREAD

**Issue by edsonmarquezani** [jenkinsci/pipeline-aws-plugin#72]
Is there any plans to implement a DSL method do publish events to SQS? It would very useful for a lot of assynchronous tasks. Implementation seems to be quite straightforward. Unfornatelly I'm not a Java programmer, otherwise I would be happy to provide a PR for it.

**Comment by ConstantinElse** [comment]
Having the same issue! Now using awscli shell workaround but it would be nice to have in DSL.
