### ISSUE TITLE
Add option to specify server side encryption algorithm in upload step

### ISSUE THREAD

**Issue by jcestibariz** [jenkinsci/pipeline-aws-plugin#74]
The s3Upload is great but I'm required to use SSE for uploaded files, ideally it should have a parameter for this purpose, like:

`s3Upload file: 'a.txt', path: 'a.txt', bucket: 'b', sseAlgorithm: 'AES-256'`

Thank you.

**Comment by hoegertn** [comment]
You can use KMS to encrypt using `s3upload(file: 'bar-dir', bucket: 'my-bucket', path: 'path/to/target', kmsId: 'alias/bar')`.

I will check for AES encryption.
