### ISSUE TITLE
pass OperationPreferences parameters to the cfnUpdateStackSet

### ISSUE THREAD

**Issue by lelik9** [jenkinsci/pipeline-aws-plugin#76]
Hi,
Could you please clarify how I can provide OperationPreferences inside the cfnUpdateStackSet method?
I didn't find it in the documentation.
Also in the documentation present not correct information in the cfnCreateStackSet section. This method is absent in your plugin, and example is referencing to the cfnCreateChangeSet method.

Thanks .

**Comment by hoegertn** [comment]
I will look into it and add support if necessary.
