### ISSUE TITLE
Support S3Upload disable multipart

### ISSUE THREAD

**Issue by timesking** [jenkinsci/pipeline-aws-plugin#84]
For some cases, I need S3Upload withtou multipart
Is there any option in S3Upload?

**Comment by ConstantinElse** [comment]
@timesking because the S3 bucket policy doesn't allow it and you cannot change it ?

**Comment by timesking** [comment]
@ConstantinElse we can ignore it now. I made other tool in pipeline supporting multipart feature.

**Comment by Constantin07** [comment]
Thanks @timesking
