### ISSUE TITLE
Request: Add Termination Protection to cfnUpdate

### ISSUE THREAD

**Issue by KenHundley** [jenkinsci/pipeline-aws-plugin#85]
Hi, 
I'd like to request an enhancement to the add an optional parameter for "enableTerminationProtection" to the cfnUpdate step. Right now we have to run an extra step after the stack creation to enable termination protection, but since it's a valid parameter of the CreateStack API call it would be nice to provide it as an option for the stack creation.

Documentation: 
https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_CreateStack.html
Parameter: EnableTerminationProtection

**Comment by hoegertn** [comment]
You can test the implementation with this build: https://ci.jenkins.io/job/Plugins/job/pipeline-aws-plugin/job/master/113/artifact/target/pipeline-aws.hpi

**Comment by hoegertn** [comment]
should be released now with 1.27
