### ISSUE TITLE
Question: How to use withAWS() in parallel

### ISSUE THREAD

**Issue by KenHundley** [jenkinsci/pipeline-aws-plugin#86]
Hi,
I've noticed that when I execute statements similar to 
```groovy
parallel "us-east-1": {
  withAWS(region:"us-east-1") {
    //Do something in us-east-1
  }
}, "us-east-2: {
    withAWS(region:"us-east-2") {
    //Do something in us-east-2
  }
}
```
this doesn't seem to work. I'm guessing the command is setting an ENV var or something similar so the statements are interfering with each other when executed in parallel. Is that the case, and if so is there any way for me to structure this so that they can execute in parallel without impacting each other?

**Comment by Constantin07** [comment]
@KenHundley try something like this then:

```
parallel(
    'us-east-1': {
        env.AWS_DEFAULT_REGION = 'us-east-1'
        sh ' do some staff ' },
    'us-east-2': {
        env.AWS_DEFAULT_REGION = 'us-east-2'
        sh ' do some staff ' }
)
```

**Comment by KenHundley** [comment]
@Constantin07, I will try this on Monday and see how it goes. Ty for the suggestion

**Comment by KenHundley** [comment]
Sorry, work got busy this week and didn’t test it yet, but I have some time now. Will let you know

**Comment by KenHundley** [comment]
@Constantin07 @hoegertn 

This suggestion worked perfectly
```java
withAWS(credentials:'prod') {
    parallel "us-east-1": {
        withEnv(['AWS_DEFAULT_REGION=us-east-1']) {
            sh "aws command"
        }
    }, "us-east-2": {
        withEnv(['AWS_DEFAULT_REGION=us-east-2']) {
            sh "aws command"
        }
    }, "ca-central-1": {
        withEnv(['AWS_DEFAULT_REGION=ca-central-1']) {
            sh "aws command"
        }
    }
}
```
Ty very much for the suggestion @Constantin07!
