### ISSUE TITLE
s3Upload cannot upload files outside of Jenkins Workspace

### ISSUE THREAD

**Issue by carstensh** [jenkinsci/pipeline-aws-plugin#87]
We have a use-case where we want to upload files from a volume mounted on the Jenkins slave to S3.

Mount shows the volume successfully mounted:
```
[pipeline] Running shell script
mount
/dev/vdb on /foo type ext4 (rw,relatime,data=ordered)
```

and I can ls the directory in a pipeline from the slave:
```
ls /foo
file1
file2
file3
```

but when trying to upload the directory using the plugin I get the following:
```
[Pipeline] s3Upload
Uploading file:/foo to s3://<bucket>/bar
Upload failed due to missing source file
```

This seems not to be an issue if I make a directory in the Jenkins workspace:
```
[pipeline] Running shell script
mkdir foo
[Pipeline] s3Upload
Uploading file:/home/jenkins/workspace/<pipeline>/foo/ to s3://<bucket name>/bar
Upload complete
```

The pipeline:
```
                stage('Upload to S3') {
                    withAWS(endpointUrl:'<endpoint>', credentials:'<s3 credentials>') {
                        s3Upload acl: 'Private', bucket: '<bucket>', file: "/foo/", path: 'bar/'
                    }
```

**Comment by carstensh** [comment]
I tried specifying a relative path to /home/jenkins/workspace/<pipeline>/foo/

s3Upload acl: 'Private', bucket: '<bucket>', file: "../../../../foo/", path: 'bar/'

but it still fails, looks like it ignores the ../ to go up a directory:

[pipeline] Running shell script
+ ls ../../../../foo/
file1
file2
file3
[Pipeline] s3Upload
Uploading file:/foo to s3://<bucket>/bar
Upload failed due to missing source file

As the files will be large, and they're on a mounted volume, copying them onto the local disk in the Jenkins workspace wouldn't be ideal.

**Comment by hoegertn** [comment]
Another idea to solve this: Symlink the folder into the workspace. Accessing files outside the workspace is not supported by the plugin.
