### ISSUE TITLE
Can't upload a file on the bucket root directory

### ISSUE THREAD

**Issue by muratso** [jenkinsci/pipeline-aws-plugin#89]
Everytime that I try to upload a single file (by using the attribute `file` or `includePathPattern`) it always shows me that I must define the path attribute and it can't be empty or start with /. I'm using the version 1.26.

Here is what I'm trying to do:
`s3Upload acl: "PublicRead", bucket: bucket, file: "${backupFile}.tar.gz"`

**Comment by smarmie** [comment]
Using a 
```
s3Upload(
  workingDir: "${WORKSPACE}",
  includePathPattern:'asd',
  bucket: 'testuploadbucket',
  path: '/'
)
```
It actually creates a folder named "      " (i forgot how many spaces) and uploads the files there.

**Comment by hoegertn** [comment]
you have to specify the target file name. I will  have a look at some UX improvements here.

**Comment by smarmie** [comment]
Well, the point would be to upload all the contents of a folder to the root of a bucket. BTW: can this also do sync? As in delete from the destination bucket what's not in the source?

**Comment by hoegertn** [comment]
should work with the current version 1.27

Beware: `workingDir` is relative to the current workspace. To upload to the bucket root use "" or no path at all.
