### ISSUE TITLE
Unable to upload files from jenkins worker

### ISSUE THREAD

**Issue by bjoernhaeuser** [jenkinsci/pipeline-aws-plugin#92]
Hi there!

We used this plugin to upload files from the jenkins master to S3. Recently we tried the same Jenkinsfile on a worker node, but the file list seems to be always empty.

From reading the code it seems to me that the listing of files happens on the master (where there is nothing), but the upload actually tries to upload from a worker.

For me it looks like this is the code:

https://github.com/jenkinsci/pipeline-aws-plugin/blob/e9673eb749115259f2a57a30564fab327ff83228/src/main/java/de/taimos/pipeline/aws/S3UploadStep.java#L260-L274

If anyone knows how to fix this I would try to code it up :)

**Comment by hoegertn** [comment]
The listing happens on the FilePath object of the context which resolves to the workspace of the job. So it should do the listing on the worker. I will try to find some time to dive into this issue.

**Comment by bjoernhaeuser** [comment]
Thank you very much!

Btw this is the log output from the run:

```
[Pipeline] stage
[Pipeline] { (upload)
[Pipeline] sh
[e_logistic-raspberries_PR-6-OZ5VOGG747E46PWNZRC25EKKYPTZKWSVVRU7ZOPKF3YRBOISUOOA] Running shell script
+ ls -la pi-gen/deploy/
total 2223988
drwxr-xr-x.  2 jenkins jenkins      4096 May 23 15:44 .
drwxr-xr-x. 12 jenkins jenkins      4096 May 23 15:16 ..
-rw-r--r--.  1 jenkins jenkins    124244 May 23 12:12 2018-05-23-11-43-rebin-rebuyian-dashboard.info
-rw-r--r--.  1 jenkins jenkins    124244 May 23 13:41 2018-05-23-13-14-rebin-rebuyian-dashboard.info
-rw-r--r--.  1 jenkins jenkins    124244 May 23 15:44 2018-05-23-15-16-rebin-rebuyian-dashboard.info
-rw-r--r--.  1 jenkins jenkins      6884 May 23 15:44 build.log
-rw-r--r--.  1 jenkins jenkins 758950518 May 23 12:12 image_2018-05-23-11-43-rebin-rebuyian-dashboard.zip
-rw-r--r--.  1 jenkins jenkins 758949081 May 23 13:41 image_2018-05-23-13-14-rebin-rebuyian-dashboard.zip
-rw-r--r--.  1 jenkins jenkins 759015786 May 23 15:44 image_2018-05-23-15-16-rebin-rebuyian-dashboard.zip
[Pipeline] withAWS
Setting AWS profile logistic-raspberries 
 Setting AWS region eu-west-1 
[Pipeline] {
[Pipeline] s3Upload
Uploading pi-gen/deploy/** to s3://rebuy-logistic-raspberries/images/ 
Upload complete
[Pipeline] }
 [Pipeline] // withAWS
```

From reading the code the `Uploading...` should never happen if the filelisting returned no result.

**Comment by bjoernhaeuser** [comment]
So, I added some debug statements and could find where the problem is coming from (though not sure how to fix this - as already stated the documentation about remote handling is not very good yet).

What I now know is that in line 304: https://github.com/jenkinsci/pipeline-aws-plugin/blob/master/src/main/java/de/taimos/pipeline/aws/S3UploadStep.java#L304

The list "children" contains the correct entries, but the "fileList" does not anymore. So I suppose the problem is in `FeedList`.

**Comment by hoegertn** [comment]
You are correct in regard to the fact that plugin code is executed on the master. This is confirmed by Cloudbees as the desired behavior. But the file listing should happen on the agent as it is a file operation on the workspace.
